apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  labels:
    app: nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
      tier: webserver
  template:
    metadata:
      labels:
        app: nginx-php
        tier: webserver
    spec:
      containers:
      - image: gcr.io/microservices-306818/age-microsrvc@sha256:482db17c2f08ddd4fd4eb842cf75fc333c850bc6e0aa5cd82e990b5fe773a3ca
        name: nginx-php
        ports:
        - containerPort: 80