apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php
  labels:
    app: nginx-php
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
      tier: webserver
  template:
    metadata:
      labels:
        app: nginx-php
        tier: webserver
    spec:
      containers:
      - image: gcr.io/microservices-306818/age-microsrvc@sha256:e3bff9440093e8ff53deaccdca6c7b8526e98ffad8ddb6b3224a6d7c6c6df441
        name: nginx-php
        ports:
        - containerPort: 80